[workspace]
resolver = "3"
members = ["argononed", "argonone-poweroff"]

[workspace.dependencies]
env_logger             = "0.11.8" 
log                    = "0.4.27"
systemd-journal-logger = "2.2.2"
tokio                  = "1.47.1"